[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md', 'markdown']
hook_add = '''
    let g:previm_open_cmd = '"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"'
nnoremap <silent> <C-p> :PrevimOpen<CR>
'''
 
[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

# [[plugins]]
# repo = 'vim-syntastic/syntastic'
# on_ft = 'python'
# hook_add = '''
# syntastic settings
# set statusline+=%#warningmsg#
# set statusline+=%{SyntasticStatuslineFlag()}
# set statusline+=%*
# let g:syntastic_always_populate_loc_list = 1
# let g:syntastic_auto_loc_list = 1
# let g:syntastic_check_on_open = 1
# let g:syntastic_check_on_wq = 0
# let g:syntastic_python_checkers = ['flake8']'''
